services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - network

networks:
  network:
    driver: bridge
